#!/bin/bash 



# V-38521 - SV-50322r1_rule - The operating system must support the requirement to centrally manage the content of audit records generated by organization defined information system components. 

# Valid results are Open, NotAFinding, Not_Applicable, and Not_Reviewed 



result='Not_Reviewed' 



test321=$(sudo grep '^\*\.\*' /etc/rsyslog.conf | awk '{print $2}' | xargs)



if [[ "$test321" =~ ^"@" ]]

then

        result="NotAFinding"

else

        result="Open"

        output="$test321"

fi



echo " V-38521 - SV-50322r1_rule - $result $output"